[alias]
gen = "generate"

[unstable]
gc = true
no-embed-metadata = true

[target.aarch64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld",
    "-C",
    "link-arg=-ld_new",
]

# Fully optimize crates installed with `cargo install`
[profile.install]
inherits = "release"
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
# panic = "abort" - could be too extreme

# Build profile overrides for specific packages, if necessary!
# [profile.release.package."ripgrep"]
# opt-level = 3
# lto = "fat"

# [profile.release.package."some-dependency"]
# opt-level = "z"
